CREATE TABLE public.real_estate (
                                    id                  int4            NOT NULL,
                                    title               varchar(50)     NOT NULL,
                                    number_of_rooms     int4,
                                    description         varchar(200)    NOT NULL,
                                    square_metres       numeric(8, 2)   NOT NULL,
                                    latit               numeric(10, 8)  NOT NULL,
                                    longit              numeric(10, 8)  NOT NULL,
                                    address             varchar(200)    NOT NULL,
                                    created_at          timestamp       DEFAULT CURRENT_TIMESTAMP NULL,
                                    type                varchar(30)     NOT NULL DEFAULT 'APARTMENT',
                                    floor               int4,
                                    has_elevator        boolean,
                                    has_garden          boolean,
                                    has_pool            boolean,
                                    number_of_floors    int4,
                                    width               numeric(6, 2),
                                    height              numeric(6, 2),
                                    is_electric         boolean,
                                    volume            numeric(10, 2),
                                    destination_use    varchar(100),
                                    crop_type        varchar(50),
                                    CONSTRAINT real_estate_id_check CHECK ((id >= 10000) AND (id <= 99999)),
                                    CONSTRAINT real_estate_pkey PRIMARY KEY (id)
);