import { Property, User, Review, Auction } from '../models';

export const MOCK_USERS: User[] = [
  { id: 1, name: 'Admin',  surname: 'hw26',    email: 'admin@hw26.it',  role: 'ADMIN',  banned: false },
  { id: 2, name: 'Mario',  surname: 'Vendita', email: 'mario@hw26.it',  role: 'SELLER', banned: false },
  { id: 3, name: 'Giulia', surname: 'Bianchi', email: 'giulia@hw26.it', role: 'BUYER',  banned: false },
  { id: 4, name: 'Luca',   surname: 'Spam',    email: 'luca@hw26.it',   role: 'BUYER',  banned: true  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 1, code: 'A001',
    title: 'Appartamento luminoso al Parioli',
    description: 'Splendido trilocale al quinto piano con ascensore, doppi servizi, terrazzo vivibile con vista sulla città.',
    category: 'APARTMENT', listingType: 'SALE',
    price: 265000, oldPrice: 285000,
    squareMeters: 95, address: 'Via Salaria 42', city: 'Roma',
    latitude: 41.92, longitude: 12.49,
    photos: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-01-10T10:00:00Z',
    sold: false,
  },
  {
    id: 2, code: 'A002',
    title: 'Loft moderno in Brera',
    description: 'Loft open space di design nel cuore di Brera. Soffitti alti 4m, mattoni a vista.',
    category: 'APARTMENT', listingType: 'RENT',
    price: 1800,
    squareMeters: 72, address: 'Via Fiori Chiari 18', city: 'Milano',
    latitude: 45.47, longitude: 9.18,
    photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-01-15T09:00:00Z',
    sold: false,
  },
  {
    id: 3, code: 'V001',
    title: 'Villa con giardino in Chianti',
    description: 'Magnifica villa storica immersa nei vigneti del Chianti. 5 camere, piscina, dependance.',
    category: 'VILLA', listingType: 'SALE',
    price: 890000,
    squareMeters: 340, address: 'Via del Poggio 7', city: 'Firenze',
    latitude: 43.48, longitude: 11.25,
    photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-01-20T11:00:00Z',
    sold: false,
  },
  {
    id: 4, code: 'A003',
    title: 'Trilocale ristrutturato San Salvario',
    description: 'Trilocale completamente rinnovato nel vivace quartiere San Salvario. Parquet, infissi nuovi.',
    category: 'APARTMENT', listingType: 'RENT',
    price: 950,
    squareMeters: 88, address: 'Corso Marconi 55', city: 'Torino',
    latitude: 45.05, longitude: 7.68,
    photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-02-01T08:00:00Z',
    sold: false,
  },
  {
    id: 5, code: 'G001',
    title: 'Box auto doppio centro storico',
    description: 'Box doppio in struttura multipiano sorvegliata h24, a 200m dal centro storico.',
    category: 'GARAGE', listingType: 'SALE',
    price: 38000,
    squareMeters: 28, address: 'Via Indipendenza 12', city: 'Bologna',
    latitude: 44.49, longitude: 11.34,
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-02-05T14:00:00Z',
    sold: false,
  },
  {
    id: 6, code: 'L001',
    title: 'Terreno edificabile vista mare',
    description: 'Terreno edificabile con permesso di costruzione già ottenuto. Vista panoramica sul golfo di Napoli.',
    category: 'LAND', listingType: 'SALE',
    price: 125000,
    squareMeters: 450, address: 'Via Posillipo 3', city: 'Napoli',
    latitude: 40.80, longitude: 14.18,
    photos: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-02-10T10:00:00Z',
    sold: false,
  },
  {
    id: 7, code: 'V002',
    title: "Masseria ristrutturata Valle d'Itria",
    description: "Antica masseria pugliese sapientemente restaurata. Trulli annessi, giardino mediterraneo.",
    category: 'VILLA', listingType: 'SALE',
    price: 580000,
    squareMeters: 210, address: 'Contrada Mitrano', city: 'Alberobello',
    latitude: 40.78, longitude: 17.23,
    photos: ['https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-02-15T09:00:00Z',
    sold: false,
  },
  {
    id: 8, code: 'A004',
    title: 'Monolocale design Porta Romana',
    description: "Monolocale di design in palazzo d'epoca ristrutturato. Zona Porta Romana, ottimi collegamenti.",
    category: 'APARTMENT', listingType: 'RENT',
    price: 1150,
    squareMeters: 38, address: 'Corso di Porta Romana 88', city: 'Milano',
    latitude: 45.45, longitude: 9.19,
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=70'],
    sellerId: 2, sellerName: 'Mario Vendita', createdAt: '2026-02-20T11:00:00Z',
    sold: false,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    postId: 1,
    userId: 3,
    author: 'Giulia Bianchi',
    title: 'Ottimo annuncio',
    rating: 5,
    description: 'Annuncio accurato, venditore disponibile.',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 2,
    postId: 1,
    userId: 4,
    author: 'Luca Spam',
    title: 'Buona posizione',
    rating: 4,
    description: 'Bella zona, prezzo onesto per i Parioli.',
    createdAt: '2026-03-05T14:00:00Z',
  },
  {
    id: 3,
    postId: 2,
    userId: 3,
    author: 'Giulia Bianchi',
    title: 'Perfetto per me',
    rating: 5,
    description: 'Loft fantastico, esattamente quello che cercavo.',
    createdAt: '2026-03-10T09:00:00Z',
  },
];

export const MOCK_AUCTIONS: Auction[] = [];